### ISSUE TITLE
切换字体

### ISSUE THREAD

**Issue by ice1000** [banana-space/btex#10]
可能依赖于 https://github.com/KaTeX/KaTeX/issues/123

**Comment by Trebor-Huang** [comment]
字体不是btex管辖的范畴，你需要修改CSS得到。局部修改字体可以靠直接输出html

**Comment by ice1000** [comment]
最好能间接控制 katex

**Comment by abccsss** [comment]
btex 只是输出 html，换字体用 css 实现很容易，但不是 btex 的任务。

**Comment by ice1000** [comment]
> btex 只是输出 html，换字体用 css 实现很容易，但不是 btex 的任务。

我的意思是比如 `\usepackage{newpxmath}` 这样的命令。

**Comment by ice1000** [comment]
如果改 css 能解决 https://github.com/KaTeX/KaTeX/issues/123 的话那自然再好不过了

**Comment by abccsss** [comment]
> 如果改 css 能解决 [KaTeX/KaTeX#123](https://github.com/KaTeX/KaTeX/issues/123) 的话那自然再好不过了

btex 不追求使用 LaTeX 字体和宏包。我在个人网站上使用

``` css
.katex, .katex .mathnormal {
    font-family:"IBM Plex Sans", KaTeX_Main, serif !important;
}
```

效果已经不错，当然还能调得更细致一些。
